reportportal/commons-dao

- src/main/java/com/epam/ta/reportportal/database/search/Condition.java
- src/test/java/com/epam/ta/reportportal/database/search/ConditionBuilderTest.java
Signed-off-by: Andrei Varabyeu <andrei.varabyeu@gmail.com>
> fix issue with time range

- src/main/java/com/epam/ta/reportportal/commons/SendCase.java
- src/test/java/com/epam/ta/reportportal/commons/SendCaseTest.java
Optional always not equals to null
> fix SendCase isPresent method

- src/main/java/com/epam/ta/reportportal/entity/item/TestItem.java
…nto test-item-attributes
#	src/main/java/com/epam/ta/reportportal/commons/querygen/FilterTarget.java
#	src/main/java/com/epam/ta/reportportal/commons/querygen/constant/LaunchCriteriaConstant.java
#	src/main/java/com/epam/ta/reportportal/dao/util/RecordMappers.java
#	src/main/java/com/epam/ta/reportportal/entity/item/TestItem.java
#	src/test/java/com/epam/ta/reportportal/dao/LaunchRepositoryTest.java
fix step item deleting
> Fix step item deleting

- src/main/java/com/epam/ta/reportportal/commons/querygen/Condition.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/entity/enums/LaunchModeEnum.java
[EPMRPP-37301] Update constants in filter
[EPMRPP-37302] Get unique launch names
[EPMRPP-37303] Get owner logins instead full names
[EPMRPP-37066] Contains ignore case
> [EPMRPP-37301], [EPMRPP-37302], [EPMRPP-37303], [EPMRPP-37066], [EPMRPP-37321] Bugfix

- src/main/java/com/epam/ta/reportportal/binary/DataStoreService.java
Reverts reportportal/commons-dao#325
> Revert "[EPMRPP-37924] Fix generating png demo attachments"

- src/main/java/com/epam/ta/reportportal/binary/DataStoreService.java
Reverts reportportal/commons-dao#328
> Revert "Revert "[EPMRPP-37924] Fix generating png demo attachments""

- src/main/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryImpl.java
> EPMRPP-37836 || Flaky widget fix

- src/main/java/com/epam/ta/reportportal/dao/IssueEntityRepository.java
- src/main/java/com/epam/ta/reportportal/dao/IssueEntityRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/IssueEntityRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/ItemAttributeRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/ItemAttributeRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepository.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/LogRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/LogRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/TestItemRepository.java
- src/main/java/com/epam/ta/reportportal/dao/TestItemRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/TestItemRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/constant/TestItemRepositoryConstants.java
- src/main/java/com/epam/ta/reportportal/entity/item/ItemAttributePojo.java
- src/main/java/com/epam/ta/reportportal/entity/item/TestItemResults.java
- src/main/java/com/epam/ta/reportportal/entity/item/issue/IssueEntity.java
- src/main/java/com/epam/ta/reportportal/entity/item/issue/IssueEntityPojo.java
- src/test/java/com/epam/ta/reportportal/dao/IssueEntityRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/ItemAttributeRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/LaunchRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/LogRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/TestItemRepositoryTest.java
- src/test/resources/db/migration/V004__items_init.sql
MERGE AFTER https://github.com/reportportal/commons-dao/pull/379
> EPMRPP-38208 || Performance optimization dao

- src/main/java/com/epam/ta/reportportal/commons/querygen/QueryBuilder.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustomImpl.java
- src/main/java/com/epam/ta/reportportal/dao/WidgetContentRepository.java
- src/main/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryImpl.java
- src/main/java/com/epam/ta/reportportal/util/WidgetSortUtils.java
- src/test/java/com/epam/ta/reportportal/dao/LaunchRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/util/WidgetSortUtilsTest.java
Junit tests for all sorts have been added
> Query builder sorting has been updated with aliases.

- src/main/java/com/epam/ta/reportportal/dao/DashboardRepository.java
- src/test/java/com/epam/ta/reportportal/dao/DashboardRepositoryTest.java
> [EPMRPP-38807] Generating one dashboard for all demo launches

- src/main/java/com/epam/ta/reportportal/config/MongodbConfiguration.java
- src/main/java/com/epam/ta/reportportal/database/DataStorage.java
- src/main/java/com/epam/ta/reportportal/database/GridFSDataStorage.java
- src/main/java/com/epam/ta/reportportal/database/dao/LogRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/database/dao/LogRepositoryCustomImpl.java
Added pageable for retrieving gridfs files. Added methods for batch removing.
> Gridfs cursor handling

- build.gradle
- src/main/java/com/epam/ta/reportportal/dao/util/WidgetContentUtil.java
- src/main/java/com/epam/ta/reportportal/entity/widget/content/LaunchesTableContent.java
Reverts reportportal/commons-dao#427
> Revert "[EPMRPP-38862] Bulk attributes update"

- src/main/java/com/epam/ta/reportportal/dao/TestItemRepository.java
- src/main/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryImpl.java
- src/test/java/com/epam/ta/reportportal/dao/TestItemRepositoryTest.java
MERGE AFTER 
https://github.com/reportportal/commons-dao/pull/450
> EPMRPP-39219 || Trend widgets fix dao

- src/main/java/com/epam/ta/reportportal/dao/AbstractShareableRepositoryImpl.java
- src/main/java/com/epam/ta/reportportal/dao/TestItemRepository.java
- src/main/java/com/epam/ta/reportportal/dao/WidgetRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/WidgetRepositoryCustomImpl.java
- src/test/java/com/epam/ta/reportportal/dao/TestItemRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/WidgetRepositoryTest.java
MERGE AFTER 
https://github.com/reportportal/commons-dao/pull/450
> EPMRPP-39255 || Filter widget relation removing impl

- build.gradle
- src/main/java/com/epam/ta/reportportal/config/DataStoreConfiguration.java
- src/main/java/com/epam/ta/reportportal/filesystem/distributed/minio/MinioDataStore.java
- src/main/java/com/epam/ta/reportportal/filesystem/distributed/minio/MinioFile.java
- src/main/resources/datastore.properties
- src/test/java/com/epam/ta/reportportal/filesystem/distributed/minio/MinioDataStoreTest.java
* Minio data store impl
* Data store config fix
* Junit test added
> Minio datastore (#525)

- src/main/java/com/epam/ta/reportportal/dao/SamlProviderDetailsRepository.java
- src/main/java/com/epam/ta/reportportal/entity/saml/SamlProviderDetails.java
- src/test/java/com/epam/ta/reportportal/dao/IntegrationRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/dao/StatisticsFieldRepositoryTest.java
- src/test/resources/db/fill/integration/integrations-fill.sql
Reverts reportportal/commons-dao#537
> Revert "EPMRPP-39617 || Saml details entity removed"

- build.gradle
- src/main/java/com/epam/ta/reportportal/commons/ReportPortalUser.java
- src/main/java/com/epam/ta/reportportal/dao/util/ResultFetchers.java
> [EPMRPP-45308] Create personal project on login if user has not assigned to any

- src/main/java/com/epam/ta/reportportal/dao/LaunchRepository.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/LaunchRepositoryCustomImpl.java
Add filter by mode for baselaunch queries
> Add filter by mode for baselaunch queries

- src/main/java/com/epam/ta/reportportal/commons/querygen/FilterTarget.java
- src/main/java/com/epam/ta/reportportal/commons/querygen/constant/LogCriteriaConstant.java
Add projectId criteria to log filter
> Add projectId criteria to log filter

- src/main/java/com/epam/ta/reportportal/dao/IntegrationTypeRepository.java
- src/test/java/com/epam/ta/reportportal/dao/IntegrationTypeRepositoryTest.java
- src/test/java/com/epam/ta/reportportal/filesystem/FilePathGeneratorTest.java
- src/test/resources/db/migration/V001007__integration_type.sql
Also fixed broken UT which fails only on Windows OS machines
> EPMRPP-76240 || Add method which returns integrationTypes by accessType

- src/main/java/com/epam/ta/reportportal/dao/ProjectUserRepositoryCustom.java
- src/main/java/com/epam/ta/reportportal/dao/ProjectUserRepositoryCustomImpl.java
* EPMRPP-84513 || Performance degradation during reporting after the fix to an assigned and an unassigned project
(cherry picked from commit 940eecda02053818c43a8b295e80bb727db45cab)
> Epmrpp 84513 (#924)

- src/main/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryImpl.java
- src/test/java/com/epam/ta/reportportal/dao/WidgetContentRepositoryTest.java
- src/test/resources/db/migration/V001005__widget_content_init.sql
https://jiraeu.epam.com/browse/EPMRPP-86363
* excluded system attributes in launches table widget
* extended test data and added unit test
> EPMRPP-86363 exclude system attributes in launches table widget

- src/main/java/com/epam/ta/reportportal/jooq/enums/JPasswordEncoderType.java
Reverts reportportal/commons-dao#958
> Revert "EPMRPP-87165 || Update JPasswordEncoderType"

- src/main/java/com/epam/ta/reportportal/util/PersonalProjectService.java
This pull request updates the `getProjectPrefix` method in `PersonalProjectService.java` to enhance the sanitization of project names by expanding the set of special characters replaced with underscores.
* [`src/main/java/com/epam/ta/reportportal/util/PersonalProjectService.java`](diffhunk://#diff-d65090359dd717c65ac52e1d3d6fbe96d61d8f7367b80794ad2408f81bf60d1dL116-R116): Updated the regular expression in the `getProjectPrefix` method to replace a broader range of special characters (`.@\-+_%!#[Copilot is generating a summary...]'*/=?^`{|}~`) with underscores, ensuring better compatibility and consistency for project names.
> Orgs login migration
